ofxGui
ofxOpenCv
ofxOsc
../local_addons/ofxCv
../local_addons/ofxFaceTracker2
../local_addons/ofxVoronoi2D
../local_addons/ofxPlasticTexture
../local_addons/ofxAutoReloadedShader
../local_addons/ofxLibwebsockets
../local_addons/ofxAVPostProcessing
